### ISSUE TITLE
支持多个机顶盒通过验证吗？？

### ISSUE THREAD

**Issue by kitkw** [larsonzh/iptv#1]
终于把你找回来了！！用了这个脚本几年了各设备都没问题（日前就一个机顶盒）。现在想多买一个机顶盒能不能同时过验证？？现在机顶盒是无线连接的，会不会一个通过验证另一个就没法验证

**Comment by larsonzh** [comment]
我两个联通机顶盒都是无线连接同一个路由器，走一条联通宽带，能通过验证同时用，各放各的节目，可全功能使。但你那个区域和运营商的宽带IPTV是否能够支持，没试过还真不敢说。

**Comment by kitkw** [comment]
大佬！今天刚申请了公网  发现盒子 wifi 连接路由器  过不了验证了.....。。
（师傅有讲申请公网 IPTV用不了无线....是什么策略变了吗？？）
设置没变。 局域单播地址也正常使用，就只有盒子不过验证

**Comment by larsonzh** [comment]
> 大佬！今天刚申请了公网 发现盒子 wifi 连接路由器 过不了验证了.....。。
> （师傅有讲申请公网 IPTV用不了无线....是什么策略变了吗？？）
> 设置没变。 局域单播地址也正常使用，就只有盒子不过验证

申请公网是啥意思？原来不能访问公网吗？跟iptv有啥关系？

**Comment by kitkw** [comment]
> > 大佬！今天刚申请了公网 发现盒子 wifi 连接路由器 过不了验证了.....。。
> > （师傅有讲申请公网 IPTV用不了无线....是什么策略变了吗？？）
> > 设置没变。 局域单播地址也正常使用，就只有盒子不过验证
> 
> 申请公网是啥意思？原来不能访问公网吗？跟iptv有啥关系？

原来为内网IP   现在申请为公网IPV4。
刚又测试了一下，发现能通过验证。 
原来是分流失败啊！！（把宽带关了，只留IPTV它就能过）
双线接入之前这问题就一直存在，流量都跑宽带这边。
现在开了公网它不能跑宽带流量（会验证不过）
帮忙看看我设置  那里有错？？感谢
![image](https://user-images.githubusercontent.com/31963066/207634430-be9135d9-2422-41b8-9ff3-a9ab28587be0.png)
![image](https://user-images.githubusercontent.com/31963066/207634698-e93a0813-cfe9-4242-bb95-5fc47c175c29.png)
![image](https://user-images.githubusercontent.com/31963066/207634867-1ee905a3-7b44-4024-93c3-e2a2c7f9de06.png)

**Comment by larsonzh** [comment]
改iptv第一WAN口，宽带第二WAN口，试试

**Comment by kitkw** [comment]
> 改iptv第一WAN口，宽带第二WAN口，试试

![屏幕截图 2022-12-15 031154](https://user-images.githubusercontent.com/31963066/207817765-6e0f6f1d-5df0-4262-9b4e-fada45040d0c.png)
 刚好有用到这些  怕出更多问题呢！！
脚本已经启用  为什么没有优先 首选wan口？？是不是在新固件里不生效？？
之前玩单线复用是有效的 ，双线就从来没生效过......
但现在 光猫 _INTERNET_B_VID_  不带ID号的  玩不了....。

有其他方法可以设置IPTV  IP 优先走 第二WAN口吗？？
明显它现在是 优先跑 首wan口 （首wan拨号关了不通，才去跑第二wan口）

**Comment by larsonzh** [comment]
华硕路由器负载均衡设置里的路由规则就这个毛病，所有版本的固件都一样，不管你如何设置，首选WAN总是优先于第二WAN，所以建议你调换一下接线，ddns的公网IP设置到第二WAN口，要么就单线复用（不要绑定vlan）。

你现在是桥接方式还是光猫拨号？桥接方式下只能单线复用，另一WAN口访问不了iptv。

当然还有其他更好的方法，就是卸载掉你现有的iptv脚本，使用双线路策略分流脚本的iptv功能，那个脚本不需要在路由器里设置路由规则，并能完善负载均衡和分流作用机制，这是简化的iptv脚本无法做到的。

**Comment by kitkw** [comment]
> 华硕路由器负载均衡设置里的路由规则就这个毛病，所有版本的固件都一样，不管你如何设置，首选WAN总是优先于第二WAN，所以建议你调换一下接线，ddns的公网IP设置到第二WAN口，要么就单线复用（不要绑定vlan）。
> 
> 你现在是桥接方式还是光猫拨号？桥接方式下只能单线复用，另一WAN口访问不了iptv。
> 
> 当然还有其他更好的方法，就是卸载掉你现有的iptv脚本，使用双线路策略分流脚本的iptv功能，那个脚本不需要在路由器里设置路由规则，并能完善负载均衡和分流作用机制，这是简化的iptv脚本无法做到的。

要么就单线复用（不要绑定vlan）？
这个方案不是要取消光猫的全部端口绑定，然后vlan id绑定吗？但现在那上网端不带ID的做不了绑定。难道还有其他用法？
![屏幕截图 2022-12-16 002822](https://user-images.githubusercontent.com/31963066/207917056-04b8fb1b-1d22-44c2-9c1e-1705d4363ca6.png)
![屏幕截图 2022-12-16 002901](https://user-images.githubusercontent.com/31963066/207917077-580a363d-53af-4817-8bce-2aab0995e080.png)

IPTV是光猫拨号  宽带是桥接路由拨号

一搜“双线路策略分流脚本”，原来大佬还有在写文章啊！！之前网站关了，才找到这里来。
马上去补一课。
现在推介用哪个方案？

**Comment by larsonzh** [comment]
很久不折腾iptv，许多东西都忘了。这破玩意儿各运营商、各地区都不一样，没有一定之规，只能自己试，麻烦的很。

**Comment by larsonzh** [comment]
> 一搜“双线路策略分流脚本”，原来大佬还有在写文章啊！！之前网站关了，才找到这里来。 马上去补一课。 现在推介用哪个方案？

https://github.com/larsonzh/amdwprprsct.git

**Comment by kitkw** [comment]
> > 一搜“双线路策略分流脚本”，原来大佬还有在写文章啊！！之前网站关了，才找到这里来。 马上去补一课。 现在推介用哪个方案？
> 
> https://github.com/larsonzh/amdwprprsct.git

这脚本也太过专业了吧，还需要定期更新！！中间出问题自己绝对不会弄.....
我上图的光猫 上网vlan 没有ID  这样还能 单线复用吗？
我还有乖乖的玩 原来的 单双线方案吧。。
iptv脚本在 单线时 没有问题
只是到了双线  好像没有优先于  首wan口...

**Comment by larsonzh** [comment]
> 这脚本也太过专业了吧，还需要定期更新！！中间出问题自己绝对不会弄..... 我上图的光猫 上网vlan 没有ID 这样还能 单线复用吗？ 我还有乖乖的玩 原来的 单双线方案吧。。 iptv脚本在 单线时 没有问题 只是到了双线 好像没有优先于 首wan口...

仅用于iptv，那些运营商网段数据用不上，用不着更新，即使更新也是自动的。

宽带桥接路由器拨号后，只能以单线复用方式接入。桥接后，光猫的其他lan口是无法导出iptv的，也就是说光猫的其他lan口就没用了，大部分光猫都是这种情况。除非是宽带光猫拨号，否则只能采用单线。

**Comment by kitkw** [comment]
>>> 桥接后，光猫的其他lan口是无法导出iptv的，

可以吧！！我现在就是“桥接模式路由器拨号宽带” “光猫路由模式拨号IPTV”双线接入 
只是脚本分流失败了

**Comment by larsonzh** [comment]
> > > > 桥接后，光猫的其他lan口是无法导出iptv的，
> 
> 可以吧！！我现在就是“桥接模式路由器拨号宽带” “光猫路由模式拨号IPTV”双线接入 只是脚本分流失败了

你光猫桥接后，猫的本地lan网与lan1口还是通的？这与常见的猫不一样，正常情况下是无法支持双线接入的。这有些奇怪，不知是猫的设置问题，还是硬件就是如此。

脚本本身并不能完全解决分流问题，分流主要是通过路由器负载均衡设置里的路由规则实现，但这个设置有个问题，第一wan的优先级总高于第二wan，受固件路由规则的限制，脚本只能用于简单情况。

**Comment by larsonzh** [comment]
一般情况下，光猫桥接路由器wan口时，会将宽带网络和iptv线路同时通过光猫的一个lan口（例如lan1口）透传到路由器wan口，形成单线复用，路由器拨号，宽带网络连接到路由器虚拟的pppoe设备（虚拟网卡）上，iptv线路则透传到wan口的网卡设备（iptv大部分采用DHCP方式，也有采用其他方式的，若使用iptv脚本，不要在路由器上用光猫iptv的vlan id设置额外的vlan绑定连接iptv线路）。此时光猫里的宽带网络和iptv线路会与光猫上的本地内网完全隔离，通过光猫上的其他lan口或光猫上的wifi将无法连通和访问外部网络、路由器内网和iptv网络，可以用机顶盒有线或无线连接光猫的其他lan口或wifi试一下，会发现无法连通iptv。这就是很多装维工程师告诉用户，光猫改桥接后iptv将无法直接连接使用的原因，甚至会说光猫上的其他lan口因此就废了。

**Comment by kitkw** [comment]
> 你光猫桥接后，猫的本地lan网与lan1口还是通的？

对！光猫的  "千兆lan口接路由wan（路由拨号） " ，光猫的 “IPTV lan口 接路由lan1(光猫拨号)”
这不是你双线的方案吗？？为什么这么惊讶！！

感谢大佬耐性回复，我现在问题解决了！！还是 “双线方案二” 小改了一下
路由规则 改成 xxx.xxx.xxx.0/25

但现在有个小问题！！就是我有用软路由，主路由是指定到软由路网关的（但IPTV分流只能在主路由网关才生效）。
而IPTV盒子是我用 当贝桌面 强制打开wifi 的不能修改网关到主路由........
（但不影响使用，只是麻烦了点以后设备都需要手动指定软路由网关  将就IPTV盒子....）
![屏幕截图 2022-12-16 234538](https://user-images.githubusercontent.com/31963066/208137808-c8c2dac2-0e17-4abd-9511-3066ce9573ed.png)
![屏幕截图 2022-12-16 225312](https://user-images.githubusercontent.com/31963066/208137870-cfac469a-0ec1-46b4-9f6b-ef7a8a676fce.png)
![屏幕截图 2022-12-16 225649](https://user-images.githubusercontent.com/31963066/208137922-41426040-a940-4ff7-8bb1-281e3a0a0471.png)
![屏幕截图 2022-12-16 234424](https://user-images.githubusercontent.com/31963066/208137966-d2eeadce-20a4-4a25-936f-b5d5db67d0ba.png)

**Comment by kitkw** [comment]
> 一般情况下，光猫桥接路由器wan口时，会将宽带网络和iptv线路同时通过光猫的一个lan口（例如lan1口）透传到路由器wan口，形成单线复用，路由器拨号，宽带网络连接到路由器虚拟的pppoe设备（虚拟网卡）上，iptv线路则透传到wan口的网卡设备（iptv大部分采用DHCP方式，也有采用其他方式的，若使用iptv脚本，不要在路由器上用光猫iptv的vlan id设置额外的vlan绑定连接iptv线路）。此时光猫里的宽带网络和iptv线路会与光猫上的本地内网完全隔离，通过光猫上的其他lan口或光猫上的wifi将无法连通和访问外部网络、路由器内网和iptv网络，可以用机顶盒有线或无线连接光猫的其他lan口或wifi试一下，会发现无法连通iptv。这就是很多装维工程师告诉用户，光猫改桥接后iptv将无法直接连接使用的原因，甚至会说光猫上的其他lan口因此就废了。

这是单线方案啊  我用的是 双线方案
而且我现在基本上用不了单线方案（_INTERNET_B_VID_ 不带ID 号）不能做到  宽带+IPTV 同时走一个 LAN口

**Comment by larsonzh** [comment]
你的复杂性超出想象，透露着一丝古怪，能解决问题就好。干嘛不把软路由当主路由，硬路由做ap，是因为iptv？软路由上也有iptv的实现方案吧。

**Comment by kitkw** [comment]
> > 一般情况下，光猫桥接路由器wan口时，会将宽带网络和iptv线路同时通过光猫的一个lan口（例如lan1口）透传到路由器wan口，形成单线复用，路由器拨号，宽带网络连接到路由器虚拟的pppoe设备（虚拟网卡）上，iptv线路则透传到wan口的网卡设备（iptv大部分采用DHCP方式，也有采用其他方式的，若使用iptv脚本，不要在路由器上用光猫iptv的vlan id设置额外的vlan绑定连接iptv线路）。此时光猫里的宽带网络和iptv线路会与光猫上的本地内网完全隔离，通过光猫上的其他lan口或光猫上的wifi将无法连通和访问外部网络、路由器内网和iptv网络，可以用机顶盒有线或无线连接光猫的其他lan口或wifi试一下，会发现无法连通iptv。这就是很多装维工程师告诉用户，光猫改桥接后iptv将无法直接连接使用的原因，甚至会说光猫上的其他lan口因此就废了。
> 
 

这是单线方案啊 我用的是 双线方案 而且我现在基本上用不了单线方案（_INTERNET_B_VID_ 不带ID 号）不能做到 宽带+IPTV 同时走一个 LAN口

原来我还能 单线复用  时,wan口（宽带+iptv） lan1(宽带2)  多好啊！！虽然下载不叠加，但上传叠加了。哈哈

**Comment by kitkw** [comment]
> 你的复杂性超出想象，透露着一丝古怪，能解决问题就好。干嘛不把软路由当主路由，硬路由做ap，是因为iptv？软路由上也有iptv的实现方案吧。

因为它是单口的    而且是伸手党只能抄  哈哈

**Comment by larsonzh** [comment]
> 这是单线方案啊 我用的是 双线方案 而且我现在基本上用不了单线方案（_INTERNET_B_VID_ 不带ID 号）不能做到 宽带+IPTV 同时走一个 LAN口

实在没搞懂你的运营商网络和iptv，以及你的光猫是咋回事儿，不知道机顶盒走旁路由后会是啥情况。

**Comment by larsonzh** [comment]
> 因为它是单口的 而且是伸手党只能抄 哈哈

其实你这个情况使用那个双线路策略路由分流方案里的iptv功能或许更简单，在脚本配置文件里可以一次完成iptv、udpxy等设置，不需要在路由器里搞这么多名堂，日后维护也更简单。

那个脚本提供了更全面的iptv功能支持，里面有个一键转换为iptv模式命令，执行完后只需完善一下iptv的细节设置，不需要的功能保持缺省状态，挺方便的，不少人这么用。

**Comment by kitkw** [comment]
> > 因为它是单口的 而且是伸手党只能抄 哈哈
> 
> 其实你这个情况使用那个双线路策略路由分流方案里的iptv功能或许更简单，在脚本配置文件里可以一次完成iptv、udpxy等设置，不需要在路由器里搞这么多名堂，日后维护也更简单。
> 
> 那个脚本提供了更全面的iptv功能支持，里面有个一键转换为iptv模式命令，执行完后只需完善一下iptv的细节设置，不需要的功能保持缺省状态，挺方便的，不少人这么用。

以后出问题了再来试试（主要是没有教程可以参照，项目的文档是弄双宽带的，自己不好弄）。
现在用的双线方案很久前就设置好在用了，只是有了公网后它不能跑到宽带网络这边来。
现在只是小改一下就能正常了，先这样用着吧。
再次感谢！大佬耐性指导！👍👍👍

**Comment by larsonzh** [comment]
> > > 因为它是单口的 而且是伸手党只能抄 哈哈
> > 
> > 
> > 其实你这个情况使用那个双线路策略路由分流方案里的iptv功能或许更简单，在脚本配置文件里可以一次完成iptv、udpxy等设置，不需要在路由器里搞这么多名堂，日后维护也更简单。
> > 那个脚本提供了更全面的iptv功能支持，里面有个一键转换为iptv模式命令，执行完后只需完善一下iptv的细节设置，不需要的功能保持缺省状态，挺方便的，不少人这么用。
> 
> 以后出问题了再来试试（主要是没有教程可以参照，项目的文档是弄双宽带的，自己不好弄）。 现在用的双线方案很久前就设置好在用了，只是有了公网后它不能跑到宽带网络这边来。 现在只是小改一下就能正常了，先这样用着吧。 再次感谢！大佬耐性指导！👍👍👍

**Comment by larsonzh** [comment]
> > 以后出问题了再来试试（主要是没有教程可以参照，项目的文档是弄双宽带的，自己不好弄）。 现在用的双线方案很久前就设置好在用了，只是有了公网后它不能跑到宽带网络这边来。 现在只是小改一下就能正常了，先这样用着吧。 再次感谢！大佬耐性指导！👍👍👍
> 


按你最早的那个负载均衡里的路由规则设置来看，似乎没啥错误，可以将脚本里的“IPTV机顶盒获取IP地址方式”iptv_get_ip_mode=3，试一下。
