### ISSUE TITLE
BJ联通IPTV 换台慢的问题

### ISSUE THREAD

**Issue by kloudo** [larsonzh/iptv#2]
首先表示感谢，按照你的教程我成功在家观看高清低延迟的IPTV。（第一次用这个平台，不知道留言的地方是否正确，请见谅）
我使用AX86U，在换台过程中遇到了需要等待的2-3秒的问题，无论是安卓电视、appleTV、还是电脑上potplayer中，切换总要等待很久，不知道有没有什么好的办法，或者我需要补充哪方面知识去完善。

**Comment by larsonzh** [comment]
> 首先表示感谢，按照你的教程我成功在家观看高清低延迟的IPTV。（第一次用这个平台，不知道留言的地方是否正确，请见谅）
> 我使用AX86U，在换台过程中遇到了需要等待的2-3秒的问题，无论是安卓电视、appleTV、还是电脑上potplayer中，切换总要等待很久，不知道有没有什么好的办法，或者我需要补充哪方面知识去完善。

描述一下具体如何使用的

**Comment by kloudo** [comment]
AX86U【IPTV】：
【使用 DHCP 路由】RFC3442&Microsoft
【启动组播路由】停用
【UDP 代理（Udpxy）】23234

播放地址：
http://192.168.50.1:23234/rtp/239.3.1.129:8008

观看稳定，有线PC和Wifi AppleTV中，“换台”就卡3秒，不知道有没有好的解决办法，能看已经很开心，这个小问题不知道有没有解决办法

**Comment by larsonzh** [comment]
> AX86U【IPTV】： 【使用 DHCP 路由】RFC3442&Microsoft 【启动组播路由】停用 【UDP 代理（Udpxy）】23234
> 
> 播放地址： http://192.168.50.1:23234/rtp/239.3.1.129:8008
> 
> 观看稳定，有线PC和Wifi AppleTV中，“换台”就卡3秒，不知道有没有好的解决办法，能看已经很开心，这个小问题不知道有没有解决办法

启动组播路由或更改下udpxy端口号试试

**Comment by kloudo** [comment]
明白了，谢谢大佬。我误打误撞在ATV安了一个TV+的播放器，换台速度起飞了，比IPLAY要好很多，好像是国人做的app。
